apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-mysql
  labels:
    pv: pv-nfs-mysql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/sharenfs"
    server: 192.168.255.100
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-mysql
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: pv-nfs-mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-dbinit
  labels:
    pv: pv-nfs-dbinit
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/shareinit"
    server: 192.168.255.100
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-dbinit
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: pv-nfs-dbinit
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-redis
  labels:
    pv: pv-nfs-redis
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: "/shareredis"
    server: 192.168.255.100
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-redis
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      pv: pv-nfs-redis
